test: add support for invalid directory

diff --git a/test b/test
--- a/test
+++ b/test
@@ -11,6 +11,12 @@ function title() {
   printf "${_S}= ${_Y}$1${_S}${_N}\n"
 }
 function check_output() {
+  # compile expect to compare with output
+  expect=()
+  while IFS= read -r line; do expect+=("$line")
+  done < <(for i in "${get_expect[@]}"; do printf "$i\n"; done)
+
+  # actually check output
   [[ "$output_only" == true ]] && return
   local all_ok=true
   for i in "${!output[@]}"; do
@@ -27,12 +33,13 @@ function check_output() {
       break
     # else
     #   printf "${_G}passed line:${_N} $b\n"
+    #
     fi
   done
   if [[ $all_ok == true ]]; then
-    printf "${_G}passed:${_N} $1\n\n"
+    printf "${_G}passed:${_C} $1\n\n${_N}"; return 0
   else
-    printf "${_R}failed:${_N} $1\n\n"
+    printf "${_R}failed:${_C} $1\n\n${_N}"; exit 1
   fi
 }
 _N='\033[0m'    # Normal
@@ -71,13 +78,15 @@ $TESTDIR/alpha/one
 $TESTDIR/alpha/two
 $TESTDIR/alpha/three
 $TESTDIR/alpha/four
+$TESTDIR/alpha/five
 EOF
 }
 function test_prep() { # {{{
   # create test git repositories
   mkdir -p $TESTDIR/alpha/bravo/charlie/delta/echo/foxtrot
-
   create_scanlist
+
+  # /alpha/one
 
   mkdir $TESTDIR/alpha/one
   cd $TESTDIR/alpha/one && git init >/dev/null
@@ -99,6 +108,8 @@ function test_prep() { # {{{
   git add staged_file
 
   echo $PWD && git status -s
+
+  # /alpha/two
 
   mkdir $TESTDIR/alpha/two
   cd $TESTDIR/alpha/two && git init >/dev/null
@@ -126,6 +137,8 @@ function test_prep() { # {{{
 
   echo $PWD && git status -s
 
+  # /alpha/three
+
   mkdir $TESTDIR/alpha/three.git
   cd $TESTDIR/alpha/three.git && git init --bare >/dev/null
 
@@ -145,6 +158,8 @@ function test_prep() { # {{{
 
   echo $PWD && git status -s
 
+  # /alpha/four
+
   cp -r $TESTDIR/alpha/three.git $TESTDIR/alpha/four.git
   cp -r $TESTDIR/alpha/three $TESTDIR/alpha/four
   cd $TESTDIR/alpha/four
@@ -161,15 +176,13 @@ function wrap_prep() {
 }
 function get_output() {
   # first argument is command to run
-  [[ "$short" == false ]] && $1
+  if [[ "$short" == false ]]; then
+    printf "${_C}------- actual output -------${_N}\n"
+    $1
+    printf "${_C}-----------------------------${_N}\n"
+  fi
   output=()
   while IFS= read -r line; do output+=("$line"); done < <($1)
-}
-function get_expect() {
-  # requires a populated expect_arr
-  expect=()
-  while IFS= read -r line; do expect+=("$line")
-  done < <(for i in "${expect_arr[@]}"; do printf "$i\n"; done)
 }
 
 wrap_prep >/dev/null
@@ -177,26 +190,27 @@ wrap_prep >/dev/null
 # scanlist validity
 function test1() {
   get_output "$ags $TESTDIR/wrong_scanlist"
-  expect=("scanlist \"$TESTDIR/wrong_scanlist\" not found")
+  get_expect=("scanlist \"$TESTDIR/wrong_scanlist\" not found")
   check_output "ags <invalid scanlist>"
 }
 
 # ags default settings
 function test2() {
   get_output "$ags $TESTDIR/scanlist"
-  expect_arr=(
+  get_expect=(
   "${_Y}S ${_N} ~/repos/ags/test_root/alpha/one"
   "${_Y}S ${_N} ~/repos/ags/test_root/alpha/two"
   "${_Y} C${_N} ~/repos/ags/test_root/alpha/three"
   "${_G}ok${_N} ~/repos/ags/test_root/alpha/four"
-  ); get_expect
+  "${_R}!!${_N} ~/repos/ags/test_root/alpha/five"
+  )
   check_output "ags"
 }
 
 # ags long format
 function test3() {
   get_output "$ags -l $TESTDIR/scanlist"
-  expect_arr=(
+  get_expect=(
   "${_S}~/repos/ags/test_root/alpha/one${_N}"
   "D  staged_deletion"
   "A  staged_file"
@@ -210,7 +224,8 @@ function test3() {
   "${_S}~/repos/ags/test_root/alpha/three${_N}"
   "skip_check" # this one has a unique commit id each time
   "${_G}ok${_S} ~/repos/ags/test_root/alpha/four${_N}"
-  ); get_expect;
+  "${_R}!!${_N} ~/repos/ags/test_root/alpha/five ${_Y}(invalid directory)${_N}"
+  )
   check_output "ags -l"
 }
 
